### PR TITLE
remove Str::of for Laravel 6 compatibility

### PR DESCRIPTION
**Pull request by chrisGeonet**

### CODE REVIEW

**Comment by freekmurze** [comment]
Seems like this PR contains breaking changes.

**Comment by chrisGeonet** [comment]
Not sure why. I only changed one thing back to how it was.
From
` if (Str::of($missingUrl)->contains('*')) {`
To
`if (str($missingUrl)->contains('*')) {`

Any ideas?

**Comment by chrisGeonet** [comment]
Update code is ready for testing

**Comment by chrisGeonet** [comment]
I can't get the tests to run locally so didn't spot that Laravel 6 doesn't have Str::replace.
Manually updated the code in a current project to test wildcards and it appears to be working now.

**Comment by freekmurze** [comment]
Thank you!

**Pull request merged**
