### PR TITLE
Pass HTTP status code to event "RouteWasHit"

### PR DESCRIPTION
**Pull request by gtapps**
Hello,

This commit now allow us to know the status code passed to the "RouteWasHit" event.

Gabriel

### CODE REVIEW

**Comment by sebastiandedeyne** [comment]
How about we pass the entire request instead?

**Comment by gtapps** [comment]
Hello,

What do you suggest then? Which variable should we pass then?

Cheers,
Gabriel

**Comment by sebastiandedeyne** [comment]
Nevermind, misunderstood the PR :D

Gonna let @freekmurze decide what to do with this one.

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
